# Generated by Django 5.1.2 on 2024-10-29 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='categoria',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='principal.categoria'),
            preserve_default=False,
        ),
    ]
